apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: first-pool
    namespace: metallb-system
spec:
  addresses:
    - 192.168.255.200-192.168.255.250  # kind 네트워크에 맞게 수정
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: my-l2-advertise	#L2Advertisement의 이름
    namespace: metallb-system
spec:
    ipAddressPools:	#광고할 IP 주소 풀의 이름
        - first-pool